version: '3'

services:

  db:
    image: postgres
    container_name: db
    env_file: .env

    environment:
      POSTGRES_DB: ${DB_POSTGRES}
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}

    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 2

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'

    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
